name: domain-layout-improvement
schema: 2026-03-01-domain-layout-improvement
status: proposed
created_at: 2026-03-01
last_updated_at: 2026-03-01
description: Improve the initial layout and sizing of domain containers and their child nodes.
